import Head from "next/head";

export default function About() {
  return (
    <div className="p-8">
      <Head>
        <title>letsthink</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-5 flex flex-col items-center justify-center">
        <h1 className="mb-5 text-3xl font-semibold text-white">About</h1>
        <p className="max-w-lg text-white">
          LetsThink allows you to collect responses from your audience through either anonymous messages or a poll in a room. After creating an account, you can
          create a room with your desired feedback type, and it can be shared with anyone using a simple URL, allowing people to participate until the room
          becomes expired. Users voting or sending messages don't need accounts either, allowing for quick responses and feedback. After expiration, results are
          saved and sent to the room owner's email, and can also be viewed here on the site itself.
        </p>
      </div>
    </div>
  );
}
