import { useEffect, useState } from "react";

import Head from "next/head";
import Suspend from "../components/utils/Suspend";
import useHttp from "../utils/hooks/useHttp";
import { Session } from "../utils/types/types";
import useSession from "../utils/hooks/useSession";

export default function Home() {
  const { session, loading, error } = useSession();

  return (
    <div className="p-10">
      <Head>
        <title>Lets Think</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspend loading={loading} errored={error}>
        <h1 className="text-4xl font-bold">Welcome {session?.session?.user.username}</h1>
      </Suspend>
    </div>
  );
}
