import { FormEvent, useContext, useEffect, useState, useRef } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Suspend from "../components/utils/Suspend";
import { AuthService, RoomsService } from "../utils/services";
import { SignIn } from "../utils/auth/auth";

export default function Login() {
  const email = useRef() as React.MutableRefObject<HTMLInputElement>;
  const password = useRef() as React.MutableRefObject<HTMLInputElement>;
  const router = useRouter();

  const handleSubmit = async (e: FormEvent<HTMLButtonElement>) => {
    e.preventDefault();

    SignIn(email.current.value, password.current.value);
  };

  return (
    <>
      <Head>
        <title>Lets Think</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-5 flex flex-col items-center justify-center">
        <h1 className="mb-5 text-2xl font-semibold text-white">Login</h1>
        <form className="flex flex-col">
          <label htmlFor="email">
            <p className="text-lg text-white">Email:</p>
          </label>
          <input id="email" className="text-black" ref={email} type="text"></input>
          <label htmlFor="password">
            <p className="text-lg text-white">Password:</p>
          </label>{" "}
          <input id="password" className="text-black" type="text" ref={password}></input>
          <button onClick={(e) => handleSubmit(e)} className="mt-5 rounded-xl bg-white p-2 hover:bg-gray-300">
            Login
          </button>
        </form>
      </div>
    </>
  );
}
