FROM python:3.9

WORKDIR /usr/app

COPY ./requirements.txt ./
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt
COPY ./ ./

# 
CMD ["uvicorn", "src.main:app",  "--reload", "--host", "0.0.0.0", "--port", "4010"]